### ISSUE TITLE
Autopopulate volume widget

### ISSUE THREAD

**Issue by micahwoodard** [AllenNeuralDynamics/view#37]
**Is your feature request related to a problem? Please describe.**
volume widget starts out blank and is annoying to put in same thing every time 

**Describe the solution you'd like**
If the acquisition.yaml already has tiles defined, populate volume widget with those tiles

**Acceptance Criteria**
- [ ] parse through tile is acquisition.yaml
- [ ] update volume plan with correct tiles upon initialization

**Comment by adamkglaser** [comment]
@micahwoodard one additional thought here. for any channel plan settings that are device dependent, they should initialize the currently set value for that property?

**Comment by micahwoodard** [comment]
Yeah I was just thinking that this morning. I can implement that really easily so that might get merged in sooner than this whole issue

**Comment by micahwoodard** [comment]
@adamkglaser I feel like we may have to store info about how the tiles where set up somewhere in the acquisition config if we want to ingest and populate the gui with a yaml file. Things like what tile mode was used, overlap, and order. As I'm getting further into this ticket, it seems difficult to backwards digest the tile list with no info at how it was composed. It also seems weird to store this info in the acquisition config since it has nothing to do with voxel and only the gui. Should there be a separate tile gui yaml that can be saved and loaded in? That also seems annoying. Let me know if you have any thoughts or ideas on how best to do it

**Comment by adamkglaser** [comment]
@micahwoodard I saw your comment in an email but am not seeing it here, but replying here anyway. I agree, I actually was thinking more that the tiling does not need to autopopulate. But instead the default values in the channel plan are the ones that would be easiest and make most sense to autopopulate. Either from the current setting of that particular device - or in the case of something like the tile prefix, step size, etc. there is a place to define a default value that it initializes to. Maybe in the same YAML location which defines what properties show up in the channel plan to begin with?

**Comment by micahwoodard** [comment]
Yeah sorry I deleted the comment because I think I can autopopulate with just the info in the tiles. And okay I can start working in this direction.
