### ISSUE TITLE
Upgrade Filter Wheel 

### ISSUE THREAD

**Issue by micahwoodard** [AllenNeuralDynamics/view#5]
**Is your feature request related to a problem? Please describe.**
Filter wheel could be more accurate to reality and more aesthetically pleasing. This issue may need to be several smaller issues

**Describe the solution you'd like**
Instead of moving small blue circle, move text and change circle color. This is more realistic. Also, get rid of text so the widget will scale better. 

**Acceptance Criteria**

- [ ] Remove text
- [ ] Change small circle color upon changing filter wheel 
- [ ] Small circle is now stationary and should be locked in top notch position

**Comment by adamkglaser** [comment]
@micahwoodard this is a draft of the envisioned graphic of the modified filter wheel widget.

<img width="949" alt="Screenshot 2024-08-01 at 9 38 11 AM" src="https://github.com/user-attachments/assets/bfcf7309-e621-45b7-8a71-5126192eea18">

**Comment by micahwoodard** [comment]
@adamkglaser what do the red outlined boxes mean and are you envisioning the circles to move at all or no?

**Comment by adamkglaser** [comment]
Sorry redboxes is meant to show that those text should be removed (they end up making the widget tiny). And yes the entire wheel will spin around when the position is changed. Perhaps there is some indicator that I left out that shows what the "active" position is. Which is a static place on the filterwheel. When filters are switched, the correct filter spins to the active position.

**Comment by micahwoodard** [comment]
Any opinion on what position is the static position? Also do you want the functionality that we have now where you can click different filters and it will change to the one you clicked?

**Comment by adamkglaser** [comment]
@micahwoodard i would say the top middle location (centered in between the 1 and 6 in the picture I sent). Regardless of the # of filters it should default to always having the active one top/middle/centered. And definitely they should change when the drop down menu is adjusted, but you are saying you also previously made it so you can click on the wheel itself? That would be a bonus but not strictly necessary depending on the required effort.

**Comment by micahwoodard** [comment]
Yeah as of right now when you click on the text, the filter moves to the one you clicked. I can probably recreate this effect in new one
