### ISSUE TITLE
Use rank order based downsampling for livestreaming

### ISSUE THREAD

**Issue by adamkglaser** [AllenNeuralDynamics/view#79]
Change downsampling class to new rank order based GPU processing. Sparse images will become dim and muted when doing traditional mean based downsampling. To retain sparse signals in downsampled images, rank order based downsampling can be used. This is now implemented in https://github.com/AllenNeuralDynamics/voxel/blob/develop/voxel/processes/downsample/gpu/gputools/rank_downsample_3d.py#L85-L88.

An init argument is ```rank```, i.e. the value within a downsampled pixel neighborhood to retain in the downsampled volume. ```rank=0``` would be a minimum value downsampling, ```rank=-1``` would be a maximum value downsampling. Maximum value would propagate too much noise, therefore we should use ```rank=-2``` to always retain the 2nd brightest pixel.

- [ ] Change livestreaming downsampling class to new rank order class
- [ ] Use ```rank=-2```

**Comment by micahwoodard** [comment]
@adamkglaser this should probably be in the exaspim-control repo since that's where the view downsampling is being implemented
